## slicing lists in python

In [1]:
# Ref : https://stackoverflow.com/questions/509211/understanding-slicing

# [a:b,c:d] ==> rows starts from (a to b-1), columns from c to d-1
# python indexes start from 0, ie. first element is considered at 0th position

import numpy as np
rand_mat = np.random.random((5,5))
print(rand_mat)

print("\nslice by rows, starting from 0th row to 1st row, take all columns ==>")
print(rand_mat[0:2,:])

print("\nslice by rows, starting from 1st row to 1st row, take all columns ==>")
print(rand_mat[1:2,:])

print("\nslice by rows, starting from 1st row to 1st row, slice by columnns starting from 2nd to 3rd ==>")
print(rand_mat[1:2,2:4])

[[0.64737187 0.67483247 0.72911859 0.10923967 0.7506589 ]
 [0.35950155 0.150321   0.01841902 0.16619165 0.16476949]
 [0.50407495 0.09926565 0.28919111 0.90930914 0.43671785]
 [0.38406483 0.93697951 0.3684494  0.68131035 0.5352624 ]
 [0.27099426 0.4422391  0.08678201 0.23389632 0.09753267]]

slice by rows, starting from 0th row to 1st row, take all columns ==>
[[0.64737187 0.67483247 0.72911859 0.10923967 0.7506589 ]
 [0.35950155 0.150321   0.01841902 0.16619165 0.16476949]]

slice by rows, starting from 1st row to 1st row, take all columns ==>
[[0.35950155 0.150321   0.01841902 0.16619165 0.16476949]]

slice by rows, starting from 1st row to 1st row, slice by columnns starting from 2nd to 3rd ==>
[[0.01841902 0.16619165]]
